# Generated by Django 4.1.7 on 2023-06-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0002_channel_delete_exam_delete_examinator_delete_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="NickName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
