# Generated by Django 4.1.7 on 2023-07-07 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0004_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(
                max_length=75, validators=[django.core.validators.EmailValidator()]
            ),
        ),
    ]
