# Generated by Django 4.1.7 on 2023-07-07 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("my_app", "0005_alter_userprofile_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Channel",
        ),
        migrations.DeleteModel(
            name="NickName",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="about",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
