# Generated by Django 4.2.2 on 2023-07-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0007_museum_postmuseum"),
    ]

    operations = [
        migrations.AddField(
            model_name="museum",
            name="description",
            field=models.CharField(blank=True, default="", max_length=400, null=True),
        ),
    ]
