# Generated by Django 4.2.2 on 2023-07-11 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0008_museum_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="museum",
            name="user",
        ),
        migrations.AddField(
            model_name="museum",
            name="profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_app.userprofile",
            ),
        ),
    ]
