# Generated by Django 4.2.2 on 2023-07-11 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0009_remove_museum_user_museum_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="museum",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_app.userprofile",
            ),
        ),
    ]
