# Generated by Django 4.2.2 on 2023-07-12 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0010_alter_museum_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postmuseum",
            name="type",
        ),
    ]
