# Generated by Django 4.2.2 on 2023-07-26 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0013_museum_urlimage_postmuseum_urlimage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="urlImage",
        ),
    ]
