# Generated by Django 4.2.2 on 2023-07-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0014_remove_userprofile_urlimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="urlImage",
            field=models.CharField(
                blank=True,
                default="https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png?20150327203541",
                max_length=200,
                null=True,
            ),
        ),
    ]
