# Generated by Django 4.2.2 on 2023-07-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0015_userprofile_urlimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date",
            field=models.CharField(default="", max_length=200),
        ),
    ]
