# Generated by Django 4.2.2 on 2023-07-27 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0016_comment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="isAdministrator",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "details",
                    models.CharField(blank=True, default="", max_length=400, null=True),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.userprofile",
                    ),
                ),
            ],
        ),
    ]
