# Generated by Django 4.2.2 on 2023-07-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0017_userprofile_isadministrator_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmuseum",
            name="isUploaded",
            field=models.BooleanField(default=False),
        ),
    ]
